### ISSUE TITLE
Is it necessary to synchronize the timing between multiple cameras?

### ISSUE THREAD

**Issue by Eastwind-17** [shockwaveHe/MCVIO#10]
Thanks for your excellent work!  Is it necessary to synchronize the timing between multiple cameras? I am using a four-camera surround view system to collect data, and the individual camera + IMU runs normally. However, when multiple cameras are running simultaneously, errors occur(seems in feature_tracker). I have not encountered this issue when running your dataset, the EuRoC dataset, or the Hiliti dataset.

**Comment by Gatsby23** [comment]
> Thanks for your excellent work! Is it necessary to synchronize the timing between multiple cameras? I am using a four-camera surround view system to collect data, and the individual camera + IMU runs normally. However, when multiple cameras are running simultaneously, errors occur(seems in feature_tracker). I have not encountered this issue when running your dataset, the EuRoC dataset, or the Hiliti dataset.

Have you check the extrinsic parameter between other cameras with the imu？

**Comment by Eastwind-17** [comment]
Of course, I've checked it. I've calibrated the extrinsics for each camera to the IMU. When I run it like this [cam_0] [cam_1] [cam_2] [cam_3], all four trajectories are correct. But when I run it like this [cam_0 cam_1 cam_2 cam_3], it throws an error. I don't think it's an issue with the extrinsics because each individual camera running with the IMU doesn't show any anomalies. Two of my four cameras have a time difference of 0.02 seconds (calibrated through Kalibr). I suspect this might be related, as Hiliti and your dataset don't have this issue, and Hiliti has done time synchronization. Could you offer any suggestions?

**Comment by shockwaveHe** [comment]
It is our design principle that all the cameras are synchronized properly. In our hardware setup, the cameras are synchronized through PPS signals so it does not cause trouble in our pipeline. We conduct a hard synchronization in the algorithm and attach a single timestamp for all the image streams. However, if your setups are asynchronized, you might need to change the synchronization mechanism in our algorithm.
