### ISSUE TITLE
Test without VPI

### ISSUE THREAD

**Issue by ryanESX** [shockwaveHe/MCVIO#2]
Thanks for your excellent work! Is it possible to run without VPI?   https://github.com/shockwaveHe/MCVIO/blob/main/MCVIO/src/Frontend/feature_tracker/feature_tracker.cpp  shows some part feature tracker without  VPI. But I'm not sure.

**Comment by shockwaveHe** [comment]
To disable VPI, you just need to set `use_vpi` to 0 in the configuration file. To build without VPI, you can delete the VPItracker.cpp and delete the code in reading VPI configuration in frontend.cpp (if I remember correctly).

**Comment by ryanESX** [comment]
Thanks for your reply. Another question on VPI: You mentioned there is a bug in VPI Pyramidal LK Optical Flow. Is it related to " feature points detected by VPI do not distribute as uniform"  in the paper?

Also, I can confirm MCVIO can work  under VPI 2.0 (on Ubuntu 20.04).

**Comment by shockwaveHe** [comment]
The bug in VPI is a minor issue in VPI optical flow output format but we already resolve it during coding. It is not related to the distribution of feature points.

**Comment by Jackyxtt** [comment]
@shockwaveHe @ryanESX 
I had tried MCVIO without VPI. It can work but it seems that the output odometry is much slower than the indoors1.bag sequence. I wonder if it is normal. It would make sense that disabling the vpi make frontend feature extraction slower.

**Comment by Jackyxtt** [comment]
But I also had an issue like this when using VPI. No features are extracted when using VPI and in RVIZ there is no features displayed on the image.
``` 
I20230222 19:35:29.938112  4777 MCVIOestimator_node.cpp:131] Get measurements
I20230222 19:35:29.938127  4777 MCVIOfrontend.cpp:485] Synchronize all images
I20230222 19:35:29.938135  4777 MCVIOfrontend.cpp:510] Empty queue
I20230222 19:35:29.942030  4778 MCVIOfrontend.cpp:40] Process image from:cam_1
I20230222 19:35:29.942386  4778 vpi_feature_tracker.cpp:623] VPI read image
[ WARN] [1677065729.943248398]: Current un pts size: 0, Prev un pts size: 0
[ WARN] [1677065729.943279931]: matching rate: -nan
I20230222 19:35:29.947937  4777 MCVIOestimator_node.cpp:131] Get measurements
I20230222 19:35:29.947975  4777 MCVIOfrontend.cpp:485] Synchronize all images
I20230222 19:35:29.948002  4777 MCVIOfrontend.cpp:510] Empty queue
I20230222 19:35:29.948745  4780 MCVIOfrontend.cpp:40] Process image from:cam_0
I20230222 19:35:29.949190  4780 vpi_feature_tracker.cpp:623] VPI read image
[ WARN] [1677065729.950036657]: Current un pts size: 0, Prev un pts size: 0
[ WARN] [1677065729.950068324]: matching rate: -nan
```
And I didn't make any changes to the source code. I wonder if anyone had come across this problem.

**Comment by shockwaveHe** [comment]
@Jackyxtt Can I have look at your config file and which VPI version you're using?

**Comment by WuZihao12** [comment]
> But I also had an issue like this when using VPI. No features are extracted when using VPI and in RVIZ there is no features displayed on the image.
> 
> ```
> I20230222 19:35:29.938112  4777 MCVIOestimator_node.cpp:131] Get measurements
> I20230222 19:35:29.938127  4777 MCVIOfrontend.cpp:485] Synchronize all images
> I20230222 19:35:29.938135  4777 MCVIOfrontend.cpp:510] Empty queue
> I20230222 19:35:29.942030  4778 MCVIOfrontend.cpp:40] Process image from:cam_1
> I20230222 19:35:29.942386  4778 vpi_feature_tracker.cpp:623] VPI read image
> [ WARN] [1677065729.943248398]: Current un pts size: 0, Prev un pts size: 0
> [ WARN] [1677065729.943279931]: matching rate: -nan
> I20230222 19:35:29.947937  4777 MCVIOestimator_node.cpp:131] Get measurements
> I20230222 19:35:29.947975  4777 MCVIOfrontend.cpp:485] Synchronize all images
> I20230222 19:35:29.948002  4777 MCVIOfrontend.cpp:510] Empty queue
> I20230222 19:35:29.948745  4780 MCVIOfrontend.cpp:40] Process image from:cam_0
> I20230222 19:35:29.949190  4780 vpi_feature_tracker.cpp:623] VPI read image
> [ WARN] [1677065729.950036657]: Current un pts size: 0, Prev un pts size: 0
> [ WARN] [1677065729.950068324]: matching rate: -nan
> ```
> 
> And I didn't make any changes to the source code. I wonder if anyone had come across this problem.

Have you solved this problem? I also encountered the same problem.
