### ISSUE TITLE
Cannot use KANNALA_BRANDT camera model 

### ISSUE THREAD

**Issue by ryanESX** [shockwaveHe/MCVIO#4]
I tried to euroc dataset with KANNALA_BRANDT camera model. 
But there has some error and vins trajectory cannot show properly. Is there anything wrong?

```
 File: "/home/ryan/mcvio_ws/src/MCVIO/MCVIO/src/Estimator/MCVIOfeature_manager.cpp" 
 line: 115 
 function <addFeatureCheckParallax>
 Content: Check parallax 
I0211 01:38:45.088106 164756 MCVIOestimator.cpp:1495] estimate extinsic param
I0211 01:38:45.088111 164756 MCVIOestimator.cpp:1495] estimate extinsic param
W0211 01:38:45.093045 164756 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 5 parameter blocks x 2 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:             -nan         -nan 

Parameter Block 0, size: 7

    0.403688 |         -nan         -nan 
  -0.0178766 |         -nan         -nan 
   -0.049086 |         -nan         -nan 
    0.812953 |          nan          nan 
   0.0133294 |         -nan         -nan 
    0.582091 |         -nan         -nan 
  -0.0100302 |            0            0 

Parameter Block 1, size: 7

    0.452747 |         -nan         -nan 
  -0.0220614 |         -nan         -nan 
    -0.12488 |         -nan         -nan 
    0.816244 |         -nan         -nan 
   0.0150224 |          nan          nan 
    0.577373 |         -nan         -nan 
  -0.0126901 |            0            0 

Parameter Block 2, size: 7

  -0.0183044 |         -nan         -nan 
  -0.0656465 |         -nan         -nan 
 -0.00082062 |         -nan         -nan 
 -0.00859936 |         -nan         -nan 
  0.00940621 |          nan          nan 
      0.7018 |         -nan         -nan 
     0.71226 |            0            0 

Parameter Block 3, size: 1

     1.01841 |         -nan         -nan 

Parameter Block 4, size: 1

           0 |         -nan         -nan 
```

**Comment by shockwaveHe** [comment]
Which camera model to you depends on what type of cameras you have. For EuRoC dataset, the camera is pinhole. It makes no sense to use KANNALA_BRANDT.

By the way, the `camera_model` package is brought from VINS-Mono. If you have questions reguarding camera model, it is better to ask them in VINS-Mono repo.

**Comment by Gatsby23** [comment]
> Which camera model to you depends on what type of cameras you have. For EuRoC dataset, the camera is pinhole. It makes no sense to use KANNALA_BRANDT.
> 
> By the way, the `camera_model` package is brought from VINS-Mono. If you have questions reguarding camera model, it is better to ask them in VINS-Mono repo.

您好，我在使用VINS的标定工具的时候，一直检测不到标定板，我在标定的时候需要注意什么不？

**Comment by shockwaveHe** [comment]
@Gatsby23 
https://github.com/ethz-asl/kalibr/wiki
All you need for calibration are here.

**Comment by shockwaveHe** [comment]
@Gatsby23 Regarding calibration board detection, make sure that your algorithm can detect and track features from the board. It is rare that the algorithm cannot detect the calibration board.

**Comment by ryanESX** [comment]
@shockwaveHe  I found the reason to make it happened. After I set `estimate_td: 1`, software will show above nan error.

**Comment by ryanESX** [comment]
I tried EuroC dataset on Vins-Mono. This dataset has no problem to run with online camera-imu calibration(`estimate_td: 1`). I compared with mcvio and Vins-Mono source code. I cannot identify which part has error(mostly are the same).

**Comment by shockwaveHe** [comment]
We don't support time difference estimation between IMU and camera in current version.

**Comment by ryanESX** [comment]
Hi I can resolve this nan issue by assigned correct ROW COL(these two variable are not initialized). in definition. I believe it cause by diving by zero( give ROW and COL to image width/height value).  
https://github.com/shockwaveHe/MCVIO/blob/main/MCVIO/src/Estimator/factor/projection_td_factor.cpp#L51-L52

But EuroC dataset, td wont converge to the small value. it will stay the initial value what I give. I look the structure of forming residual( https://github.com/shockwaveHe/MCVIO/blob/main/MCVIO/src/Estimator/MCVIOestimator.cpp#L1574-L1589).  Based on what I've observed, it appears that those part are similar to vins mono. But you refactored code to be extendable.  It is possible to give me some suggestion to add  time difference estimation back to mcvio?

**Comment by shockwaveHe** [comment]
Actually we solved this issue in our unpublished code. I can share this part with you. Provide your email to me and I will send you through email.

**Comment by ryanESX** [comment]
@shockwaveHe I was sick recently. Sorry for late reply.  It would be great if you can provide this part of code. my e-mail is: ryan277845@gmail.com

**Comment by WuZihao12** [comment]
> Actually we solved this issue in our unpublished code. I can share this part with you. Provide your email to me and I will send you through email.

Hello, can you share it with me?  zihaowu.247@gmail.com

**Comment by DuyTPresent** [comment]
> Actually we solved this issue in our unpublished code. I can share this part with you. Provide your email to me and I will send you through email.

Hello, Can you share it with me? 
duytran.daihoc@gmail.com
