### ISSUE TITLE
how to use loop closure and  fast relocalization

### ISSUE THREAD

**Issue by ryanESX** [shockwaveHe/MCVIO#5]
I try to turn on `loop_closure` and `fast_relocalization`. But it seems like no affect to the result. Later, I found  mcvio doesn't take  these two parameters at all. Is it possible to  use loop closure in mcvio? In your paper `E. Re-Localization` , It also mention this part.

**Comment by shockwaveHe** [comment]
Hi, at some points we decided to drop the loop closure and fast relocalization part of the algorithm for development concern. In current release version I don't provide the module for that.
