### ISSUE TITLE
An error occurred while running the program

### ISSUE THREAD

**Issue by Albertcqq** [shockwaveHe/MCVIO#6]
### 

 --------
File: "/root/slam/mcvio_ws/src/MCVIO-main/MCVIO/src/Estimator/MCVIOfeature_manager.cpp", line: 67, function <addFeatureCheckParallax>
I0313 17:46:14.191606 12321 MCVIOfeature_manager.cpp:68] NUM_OF_CAM: 2
I0313 17:46:14.191704 12321 MCVIOfeature_manager.cpp:77] Process camera: 0
I0313 17:46:14.191745 12321 MCVIOfeature_manager.cpp:78] Feature num:73
I0313 17:46:14.191864 12321 MCVIOfeature_manager.cpp:77] Process camera: 1
I0313 17:46:14.191913 12321 MCVIOfeature_manager.cpp:78] Feature num:63
 --------
 File: "/root/slam/mcvio_ws/src/MCVIO-main/MCVIO/src/Estimator/MCVIOfeature_manager.cpp" 
 line: 115 
 function <addFeatureCheckParallax>
 Content: Check parallax 
[ WARN] [1678700774.192398250]: VIO initialization buffer frames
I0313 17:46:14.195377 12324 vpi_feature_tracker.cpp:623] VPI read image
[MCVIO_estimator-1] process has died [pid 12151, exit code -11, cmd /root/slam/mcvio_ws/devel/lib/mcvio/mcvio_estimator __name:=MCVIO_estimator __log:=/root/.ros/log/9cb17828-c147-11ed-9d11-48b02d763c98/MCVIO_estimator-1.log].
log file: /root/.ros/log/9cb17828-c147-11ed-9d11-48b02d763c98/MCVIO_estimator-1*.log

I run this code on Nvidia Jetson Xavier NX ,ubuntu 18.04, and the vpi version is 1.1.15

<img width="643" alt="屏幕截图 2023-03-13 175049" src="https://user-images.githubusercontent.com/18108740/224666671-6711b0aa-94e8-454a-b5c9-0bf668ddf9f2.png">
<img width="620" alt="屏幕截图 2023-03-13 175041" src="https://user-images.githubusercontent.com/18108740/224666742-2f954bb6-a1e6-4da6-8667-25979bf4679d.png">

gdb debugging information is as follows：
<img width="569" alt="屏幕截图 2023-03-13 181321" src="https://user-images.githubusercontent.com/18108740/224672305-40a4de5b-2880-460e-b421-78f458871e87.png">

**Comment by shockwaveHe** [comment]
It seems like there is some out of vector bugs with the tracker code that I never came into before, but it is hard to tell by just looking at the figures you provided.

**Comment by Albertcqq** [comment]
I test this project on VPI 1.0.15 and VPI1.1.15，it‘s not work，
But it works successfully on VPI 2.1.6
On the nvidia forum, I found that someone was having the same problem with VPI1.1.15 as me,link is as follow：
https://forums.developer.nvidia.com/t/vpi-fatal-assertion-error-when-trying-to-use-cuda-wrapped-unified-memory-in-remap-on-vic/200021/4

**Comment by shockwaveHe** [comment]
Thanks for letting me know! Will look into that further.

**Comment by WuZihao12** [comment]
> 我在VPI 1.0.15和VPI1.1.15上测试了这个项目，它不起作用， 但在VPI 2.1.6上成功运行 在nvidia论坛上，我发现有人和我有VPI1.1.15相同的问题，链接是如下： [https://forums.developer.nvidia.com/t/vpi-fatal-assertion-error-when-trying-to-use-cuda-wrapped-unified-memory-in-remap-on-vic/200021 /4](https://forums.developer.nvidia.com/t/vpi-fatal-assertion-error-when-trying-to-use-cuda-wrapped-unified-memory-in-remap-on-vic/200021/4)

Hello, I would like to ask how you downloaded different versions of VPI. I can only find the latest release version.

**Comment by Albertcqq** [comment]
> > 我在VPI 1.0.15和VPI1.1.15上测试了这个项目，它不起作用， 但在VPI 2.1.6上成功运行 在nvidia论坛上，我发现有人和我有VPI1.1.15相同的问题，链接是如下： [https://forums.developer.nvidia.com/t/vpi-fatal-assertion-error-when-trying-to-use-cuda-wrapped-unified-memory-in-remap-on-vic/200021 /4](https://forums.developer.nvidia.com/t/vpi-fatal-assertion-error-when-trying-to-use-cuda-wrapped-unified-memory-in-remap-on-vic/200021/4)
> 
> Hello, I would like to ask how you downloaded different versions of VPI. I can only find the latest release version.

https://repo.download.nvidia.com/jetson/
